[build-system]
build-backend = 'mesonpy'
requires = ['meson-python', 'numpy']

[project]
name = 'dustpy-gpu'
version = '1.0.9.2'
description = 'Dust evolution in protoplanetary disks'
readme = { file = 'README.md', content-type = 'text/markdown' }
keywords = [
  "numerical",
  "simulation",
  "science",
  "physics",
  "astrophysics",
  "astronomy",
]
authors = [
  { name = "Rixin Li", email = "rixin.li.astro@gmail.com" },
  { name = "Sebastian Stammler", email = "sebastian.stammler@gmail.com" },
  { name = "Til Birnstiel", email = "til.birnstiel@lmu.de" },
  { name = "León-Alexander Hühn", email = "huehn@uni-heidelberg.de" },
]
maintainers = [
  { name = "Rixin Li", email = "rixin.li.astro@gmail.com" },
]
license = { text = "GPLv3" }
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Fortran",
  "Topic :: Education",
  "Topic :: Scientific/Engineering",
  "Topic :: Scientific/Engineering :: Physics",
]
dependencies = [
  "matplotlib",
  "numpy",
  "requests",
  "simframe-gpu>=1.0.6.1",
]

[project.urls]
Repository = "https://github.com/astroboylrx/dustpy-gpu/"
Documentation = "https://astroboylrx.github.io/dustpy-gpu/"
